### ISSUE TITLE
Install Datadog APM

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1083]
## Value Statement

**As** a DevOps Engineer
**I want to** enable easy and efficient diagnosis of our application
**So that** actionable tickets are created without time wasted on inefficient diagnosis

## Acceptance Criteria

**GIVEN** we recieve errors in our application
**WHEN**
**THEN**

## Checklist

-   [ ] Put the snippet in the correct location in our code base
```
from ddtrace import tracer

# Network socket
tracer.configure(
  dogstatsd_url="udp://localhost:8125",
)

# Unix domain socket configuration
tracer.configure(
  dogstatsd_url="unix:///var/run/datadog/dsd.socket",
)
```
-   [ ] Add the [Datadog Tracing library](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/python/?tab=containers#instrument-your-application) `pip install ddtrace` to our requirements.txt
-   [ ] Make sure our pip version is 18.0.0 or greater
-   [ ] Instrument our application use the included ddtrace-run command. To use it, prefix our Python entry-point command with `ddtrace-run`.
  *  From their documentation:
    For example, if your application is started with python app.py then:
```
    ddtrace-run python app.py
```
- [ ] Check it's set up correctly by running:
```
ddtrace-run --info
```

## Assumptions

- the Forwarder is set up correctly

## Additional Info/Resources

- [Instrument Your Application](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/python/?tab=containers#instrument-your-application)

## Open Questions

- Why would the migrations step cause this to fail? 
- What tests beyond successful deployment?

## Out of Scope / Next Steps

- Create a Spike to open up Story tickets to [fully utilize Datadog's capabilities](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/python/?tab=containers#further-reading)
- We still have yet to fully utilize the logs being forwarder to Datadog, so Spike/tickets should be created in that regard
- Do we want APM for the frontend as well? 
- Our glossary and documentation updated 

## Cross Functional Checklist

Monitoring:

-   [ ] statsd metrics
-   [ ] datadog graphs
-   [ ] datadog alerts

**Comment by Eallan919** [comment]
@ldraney would you please add your estimate to this ticket please? Thank you!

**Comment by ldraney** [comment]
Here's my rough-draft approach to solving this problem:
First, try to put the snippet somewhere else besides application.py…

Then, try to run migrations locally and see if my changes are still stopping migrations 

Finally, if the above attempts didn't work, I'll make a ticket about “limited migrations errors” and add it as a blocker to my apm ticket
make some artifacts for migrations
modify migrations script and try to get output

**Comment by ldraney** [comment]
When trying to run locally, I forgot to add the package to our application!

migrations_1  | Usage: flask db upgrade [OPTIONS] [REVISION]
migrations_1  |
migrations_1  | Error: While importing "application", an ImportError was raised:
migrations_1  |
migrations_1  | Traceback (most recent call last):
migrations_1  |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
migrations_1  |     __import__(module_name)
migrations_1  |   File "/app/application.py", line 28, in <module>
migrations_1  |     from ddtrace import tracer
migrations_1  | ModuleNotFoundError: No module named 'ddtrace'
migrations_1  |

**Comment by ldraney** [comment]
[Migrations passed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4166694623)!  In order to get it to pass we added the `ddtrace` library to our notification-api/requirements-app.txt  (if this is the right place yet I still need to verify with Kyle). 

So, Danny (the customer service at Datadog GovCloud) and I are trying to add the command to our flask app:  
```
ddtrace-run python app.py
```
In the right place.  We are thinking maybe maybe notification-api/scripts/run_app.sh, or maybe the dockerfile for our app:

**Comment by ldraney** [comment]
Okay, we added the command to run_app.sh, as mentioned above, and are getting an error:
```
app_1         | ERROR 2023-02-13 19:13:20,434 /usr/local/lib/python3.8/site-packages/ddtrace/internal/writer.py:594: failed to send, dropping 4 traces to Datadog Agent at http://localhost:8126/v0.5/traces after 3 retries ([Errno 99] Address not available)
```

Which makes sense, because there is no datadog agent locally, I believe.  

I'm going to push changes, pass tests, then try deploying to dev and maybe it will work.

**Comment by ldraney** [comment]
ecs deployed successfully, but since I can't ssh into an ecs container, I can't verify that apm is working yet until it gets to our dashboard. 
It may already be in the dashboard... I don't see it
so I'm going to begin adding the metric correlation to logs by adding DD_PROFILING_ENABLED=true to the ddtrace-run python app.py command:
```
ddtrace-run flask run -p 6011 --host=0.0.0.0
```

**Comment by ldraney** [comment]
If APM isn't getting to our dashboard in like ten minutes, I'll add this snipped to our application.py:
```
from ddtrace import patch_all
patch_all()
```
and then remove the `ddtrace-run` from the `flask run` command

**Comment by ldraney** [comment]
In the ECS logs for service "dev-notification-api-service", its says:
```
2023-02-13 21:00:37 UTC | PROCESS | ERROR | (pkg/forwarder/transaction/transaction.go:357 in internalProcess) | API Key invalid, dropping transaction for https://process.ddog-gov.com/api/v1/container
```

it's a strange error that's not in the previous logs, so I'll just try re-deploying and see what's up.

**Comment by ldraney** [comment]
Okay, now it successfully deployed!  But, the datadog agent can't communicate with our dashboard!!!
```
2023-02-13 21:25:41 UTC | CORE | ERROR | (pkg/forwarder/transaction/transaction.go:357 in internalProcess)
 | API Key invalid, dropping transaction for https://7-40-0-app.agent.ddog-gov.com/api/v1/check_run?api_key=eAx(_h3Wut7mIz>{
```

I can probably just put the API key in the task definition, but the agent should already have it, so this error is weird.

**Comment by ldraney** [comment]
We are still getting this API key error, even after kyle tried updating the agent's api key... so...  I sent a message to Danny:
Hey Danny!

Thanks for the advice. 

our agent container is trying to send to our dashboard, but it's getting this error:

 2023-02-13 22:43:23 UTC | PROCESS | ERROR | (pkg/forwarder/transaction/transaction.go:357 in internalProcess) | API Key invalid, dropping transaction for https://process.ddog-gov.com/api/v1/container

This is weird because our agent is already sending metric information to our dashboard. 
Can you help me with this?

I've tried updating our agents DD_API_KEY, but still the same error. 

Where is the agent or APM looking for this key?

**Comment by ldraney** [comment]
Hi Lucas,
 
The process agent actually does not send any APM data, so I'm leaning more towards a firewall/proxy issue here. Can you make sure all the endpoints listed here have been whitelisted so the agent can connect to them: https://docs.datadoghq.com/agent/guide/network/?tab=agentv6v7#overview?
 
Can you also try curling the API key validation endpoint and sharing the output: https://docs.datadoghq.com/api/latest/authentication/?code-lang=curl#validate-api-key?
example:
curl -X GET "https://api.ddog-gov.com/api/v1/validate" \
-H "Accept: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}"
 
Finally, can you confirm the last 4 characters of the API key you set in the agent config?
 
Best,
Danny Serrano | Solutions Engineer

**Comment by tabinda-syed** [comment]
It seems to be a network/firewall issue. Lucas received a list of endpoints, to check whether they might be whitelisted. He also verified a key that Danny shared.

**Comment by ldraney** [comment]
The tracer is working correcdtly, but it's not receiving data in ECS:
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/691c4868-1e86-4566-ad7a-5bb1ba564bec)

So I emailed Danny at Datadog Gov, who said:

Hi Lucas,
 
Thanks for the update! If traces were being sent in, you would see them here: https://vanotify.ddog-gov.com/apm/traces 
 
Continuous Profiling has some additional setup: https://docs.datadoghq.com/profiler/
But let's focus on getting the traces in first.
 
From the log you shared, it seems the tracer is working correctly, but it's not receiving data: trace agent running
Can you confirm traffic is being generated on the application? Can you also the traces are being sent to the correct port?
 
Can you also share the following:
your updated task definition
your tracer config (your dockerfile)
confirm your application meets the compatibility requirements here: https://docs.datadoghq.com/tracing/trace_collection/compatibility/python/ 
send tracer debug logs: https://docs.datadoghq.com/tracing/troubleshooting/tracer_debug_logs/#enable-debug-mode
agent debug logs: set DD_LOG_LEVEL to debug
 
Best,
Danny Serrano | Solutions Engineer

**Comment by ldraney** [comment]
I'm going to try updating the Datadog Agent on every service in our cluster and see if we start getting logs forwarded.

**Comment by ldraney** [comment]
I also we have not agent in our celery task.  That's interesting.

**Comment by ldraney** [comment]
I'm getting "no data received" on celery as well:
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/c6f9efa6-35fc-4a10-851f-e80e125e237e)

**Comment by ldraney** [comment]
From this ddtrac docs troubleshooting I saw this:
"
Traces not showing up in the app¶
The most common reason for traces not being received by Datadog is an agent communication issue:
Ensure the Datadog agent is running and reachable over the network if not on the same host.
Ensure that ddtrace is configured with the hostname and port of the agent. See Configuration for the configuration variables.
To verify that a connection can be made to the agent with your environment variable configurations run the command ddtrace-run --info.
"

**Comment by ldraney** [comment]
I updating our application.py dd-tracer part to hopefully start looking for the right hostname:
import os

os.environ["DD_TRACE_AGENT_HOSTNAME"] = "my-datadog-agent-hostname"
os.environ["DD_TRACE_AGENT_PORT"] = "8126"  # the default port for trace collection

**Comment by Eallan919** [comment]
close

**Comment by ldraney** [comment]
I'm continuiing my conversation with Danny, and will have a screenshare at 3:30 EST today. 
I've updated our application and am currently playing with the above configurations to get tracing to our agent (it is still receiving none). 
I have noticed that logs are not in our dashboard as they should be (separate issue from a previous ticket), which will be part of the discussion this afternoon.

**Comment by ldraney** [comment]
I'm trying to deploy my changes, but migrations is failing in our pipeline but not locally:
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/87287506-ccc1-4142-9ccb-9271964247f3)

**Comment by ldraney** [comment]
finally got past the migrations issue by merging my branch with the latest master

**Comment by ldraney** [comment]
apm is working :)  
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/dff54cef-75d7-4ef5-a702-edefcd36bfd8)

And my new code is passing our tests. 

Next step is to add the same code to our staging, perf, and prod task definitions, and then I'll open the PR for review.

**Comment by ldraney** [comment]
With Kyle we realized the blocker was my migrations local wasn't being accurate. 
I ran a Docker Prune and then rebuilt images on master, then switched to my branch and docker-compose up, and migrations failed locally with the error:
```
migrations_1  | Usage: flask db upgrade [OPTIONS] [REVISION]
migrations_1  |
migrations_1  | Error: While importing "application", an ImportError was raised:
migrations_1  |
migrations_1  | Traceback (most recent call last):
migrations_1  |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
migrations_1  |     __import__(module_name)
migrations_1  |   File "/app/application.py", line 3, in <module>
migrations_1  |     from ddtrace import patch_all
migrations_1  | ModuleNotFoundError: No module named 'ddtrace'
migrations_1  |
```
This is a good thing as I can finally diagnose what might be going wrong.  In this case, maybe ddtrace==1.8.0 in requirements-app.txt is not the right version...

**Comment by ldraney** [comment]
our current dependency is out of date:
```
google-cloud-bigquery 3.4.1 depends on packaging<22.0.0dev and >=14.3
```
latest is google-cloud-bigquery 3.6.0
I'd like to update it as a part of my ticket, because:
```
ddtrace 1.8.0 depends on packaging>=17.1
```
But I can also lower ddtrace version, but it seems better to update.
***
I updated to 3.6.0, and it's passing test, but I'm checking https://pypi.org/project/google-cloud-bigquery/ and the repo to check for potentially breaking changes to our tests.

**Comment by ldraney** [comment]
The next issue is this step is stalling: 
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/f5b2925c-21a8-469b-bcdb-84bb3cf384cf)

**Comment by ldraney** [comment]
First, deploy is now working as normal :)  It is only on a new dev_deploy of my branch that it takes so long.  But on a second deploy it runs like a charm.  May have to do with the task definitions.

**Comment by ldraney** [comment]
I'm getting a weird error from our tests.yaml workflow:
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy Release' is no longer signed.
Error: Process completed with exit code 100.
Has anyone seen this before?
The step failing is 'install libcurl' which is running sudo apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev , but it may have to do with Github Actions using   http://azure.archive.ubuntu.com/ubuntu jammy-security/universe as it's image.

**Comment by audiolion** [comment]
@ldraney I am also seeing this error, I think something broke upstream for many people
