### ISSUE TITLE
Regular Update for API Dependencies

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1798]
## User Story - Business Need

We wish to keep dependencies up to date so we do not need such massive overhauls of our system. This is a recurring task to update all dependencies we are able to update. Any conflicts shall get a dedicated ticket. This task should be a day of work at most because it only updates non-breaking changes.

- [x] Ticket is understood and QA has been contacted

### User Story

**As** VA Notify,
**I want** to keep our service up to date
**So that** we are secure and as free of bugs as possible.

### Additional Info and Resources

- Relevant section of [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-dependencies)
- Troubleshooting tips:
  - When looking at changes in `poetry.lock`, revert major changes, then minor, then patch/security

## Engineering Checklist

- [x] Open "Tech Debt" issues reviewed to identify packages already known to have breaking changes (don't try to upgrade these).  These should already be pinned down in the `pyproject.toml`file. Do not update dependencies that are pinned down which have tech debt labeled tickets already.
- [x] Review [open Dependabot PRs](https://github.com/department-of-veterans-affairs/notification-api/pulls/app%2Fdependabot) to determine where the changes will take place. You may need to rebase older PRs.  The PRs explain how to do this. **Never** modify the dependabot PRs outside commenting as dependabot describes. Never directly edit the `poetry.lock` file as the dependabot PRs may do; poetry handles this in the below step. Some dependabot PRs occur outside of the .lock file; those will need to be handled as needed since Poetry won't manage other files.
- [x] Update performed per the [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-dependencies)
- [x] Passes all tests locally
- [x] Passes QA Suite regression testing against Dev
- [ ] If there are any failures, compare the [poetry.lock in master](https://github.com/department-of-veterans-affairs/notification-api/blob/master/poetry.lock) against your local `poetry.lock`.  Never directly modify the .lock file.
  - [ ] Identify the discrepancies and lock those versions in `pyproject.toml`, create a ticket, and label it "tech debt"
  - [ ] Any non-top level dependencies that have to be locked should have a comment added to `pyproject.toml` and have a checkbox to remove that dependency from `pyproject.toml` in the acceptance criteria
  - [ ] Created ticket has the package name in the title (i.e. "Update foobar package") and information as to the errors encountered when updating.

## Acceptance Criteria

- Repo dependencies are updated and we have no broken functionality. 
- Issues opened by Dependabot are resolved. 
- Tickets with the "tech debt" label created for any updates we could, or should, not do.

## QA Considerations

- [x] Dependabot PRs updated.  (They should automatically close if a given dependency was upgraded at least to the version given by the PR once the PR is merged to master)
- [x] Check to see if these updates cancel out any Twistlock issues
- [x] QA Regression tests pass after deploying this code.

**Comment by MackHalliday** [comment]
Today: 

-  Working thru issues with `dd trace`. Posted in [va-notify-engineers ](https://oddball.slack.com/archives/C036AE08HA7/p1718392204434339) channel
-  Need to address potential issues with local python version. Keeps defaulting to 3.12 

Thursday (When I return) 
- Address environment issues

**Comment by MackHalliday** [comment]
I get this error when I try to run `poetry update` locally 

```
poetry update                                  
Updating dependencies
Resolving dependencies... (11.9s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing ddtrace (1.18.2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/_distutils/extension.py:134: UserWarning: Unknown Extension options: 'parallel'
    warnings.warn(msg)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/internal/_encoding.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  warning: ddtrace/internal/_utils.pxd:2:37: Declarations should not be declared inline.
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/internal/_rand.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/internal/_tagset.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/profiling/_build.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/profiling/collector/_task.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/profiling/collector/_traceback.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/profiling/collector/stack.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/profiling/exporter/pprof.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmpamk4_mgv/ddtrace-1.18.2/ddtrace/profiling/_threading.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  [1/9] Cythonizing ddtrace/internal/_encoding.pyx
  [2/9] Cythonizing ddtrace/internal/_rand.pyx
  [3/9] Cythonizing ddtrace/internal/_tagset.pyx
  [4/9] Cythonizing ddtrace/profiling/_build.pyx
  [5/9] Cythonizing ddtrace/profiling/collector/_task.pyx
  [6/9] Cythonizing ddtrace/profiling/collector/_traceback.pyx
  [7/9] Cythonizing ddtrace/profiling/collector/stack.pyx
  [8/9] Cythonizing ddtrace/profiling/exporter/pprof.pyx
  [9/9] Cythonizing ddtrace/profiling/_threading.pyx
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py:266: UserWarning: Unknown distribution option: 'package_urls'
    warnings.warn(msg)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:92: UserWarning: version of ddtrace already set
    warnings.warn(f"version of {dist_name} already set")
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:76: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
  !!
  
          ********************************************************************************
          The following seems to be defined outside of `pyproject.toml`:
  
          `license = 'BSD'`
  
          According to the spec (see the link below), however, setuptools CANNOT
          consider this value unless `license` is listed as `dynamic`.
  
          https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
  
          To prevent this problem, you can list `license` under `dynamic` or alternatively
          remove the `[project]` table from your file and rely entirely on other means of
          configuration.
          ********************************************************************************
  
  !!
    _handle_missing_dynamic(dist, project_table)
  /private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:83: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
    corresp(dist, value, root_dir)
  Traceback (most recent call last):
    File "/Users/mack/.local/pipx/venvs/poetry/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/Users/mack/.local/pipx/venvs/poetry/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/mack/.local/pipx/venvs/poetry/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
      return _build_backend().build_wheel(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 511, in <module>
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 158, in setup
      dist.parse_config_files()
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/_virtualenv.py", line 22, in parse_config_files
      result = old_parse_config_files(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 632, in parse_config_files
      pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 69, in apply_configuration
      return _apply(dist, config, filepath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 57, in apply
      _apply_project_table(dist, config, root_dir)
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 83, in _apply_project_table
      corresp(dist, value, root_dir)
    File "/private/var/folders/mg/t6dtykqn50j_q3rxjqyfsb0w0000gq/T/tmp7juuflag/.venv/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 184, in _license
      _set_config(dist, "license", val["text"])
                                   ~~~^^^^^^^^
  KeyError: 'text'
  

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

```

**Comment by k-macmillan** [comment]
Took over this since @MackHalliday is out of office. Dependencies updated. All tests passed.

**Comment by cris-oddball** [comment]
PR Approved, Merged. 

- Twistlock ignored issues removed for updated dependencies to see if they clear when the container is scanned.
- Dependabot issues rebased - they all closed for the updated dependencies. One was missed for the requirements file for load testing, but that lambda is not currently in use.
- Deployed to Perf via pipeline

**Comment by cris-oddball** [comment]
**QA PASSED**
