### ISSUE TITLE
BUG: missing email subject personalization throws errors

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#2286]
## Description
When sending an email using a template that has a subject personalization and that subject personalization is **not** sent in the POST payload, one of two things may happen:
- If the email body also has a personalization field which is sent in the payload, then the service returns a 500 Internal Server Error and the logs indicate a `NullValueForNonConditionalPlaceholderException` was raised.
- If the email body contains no personalization then the message is send but the subject is then modified to include the personalization field and span headers: 
```
QA Test Thoughts and no body personalization <span class='placeholder'>((thoughts))</span>
```

Either way, the service does not correctly handle the missing payload fields for email subjects.

Unclear if this is a Utils repo issue, which it may be based on the logs seen.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

**First Condition**: Email template has personalization fields in the subject and body. 
VANotify Service, template ID `b2c9ff49-b37b-4352-ab0c-3d3d0710fe4c`
The Happy Path payload would be
```
{
    "template_id": "b2c9ff49-b37b-4352-ab0c-3d3d0710fe4c",
    "email_address": "<your email here>",
    "personalisation": {
        "thoughts": "TEST"
        "body": "QA says Hello"
  }
}
```

1. In Postman, set service to VANotify with email_template_id set to `b2c9ff49-b37b-4352-ab0c-3d3d0710fe4c`
2. Use the POST send email route with that template ID and this payload (missing the subject personalization "thoughts"):
```
{
    "template_id": "b2c9ff49-b37b-4352-ab0c-3d3d0710fe4c",
    "email_address": "<your email here>",
    "personalisation": {
        "body": "Hello There!"
  }
}
```
3. Note that the response is a 500 Internal Server Error.
A notification ID will be found in the logs, the sequence is something like this (or just search for `NullValueForNonConditionalPlaceholderException`)
```
raise NullValueForNonConditionalPlaceholderException
notifications_utils.field.NullValueForNonConditionalPlaceholderException
[2023-08-04 19:19:11,610: INFO/ForkPoolWorker-4] Notification id: d5ff1b57-df7a-4af6-bb3c-f87acbf73c6e, max retries: 2886, retries: 210
```
There will also be an exception found in the logs
```
Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/.venv/lib/python3.10/site-packages/ddtrace/contrib/internal/flask/wrappers.py", line 92, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/.venv/lib/python3.10/site-packages/ddtrace/contrib/internal/flask/patch.py", line 537, in _patched_request
    return wrapped(*args, **kwargs)
  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/.venv/lib/python3.10/site-packages/ddtrace/contrib/internal/flask/wrappers.py", line 65, in patch_func
    return _wrap_call(
  File "/.venv/lib/python3.10/site-packages/ddtrace/contrib/internal/flask/wrappers.py", line 56, in _wrap_call
    return wrapped(*args, **kwargs)
  File "/app/app/v2/notifications/post_notifications.py", line 138, in post_notification
    create_post_email_response_from_notification, subject=html.unescape(template_with_content.subject)
  File "/.venv/lib/python3.10/site-packages/notifications_utils/template.py", line 280, in subject
    return Markup(compose1(field, do_nice_typography, normalise_whitespace))
  File "/.venv/lib/python3.10/site-packages/notifications_utils/template.py", line 53, in compose1
    return_value = f(return_value)
  File "/.venv/lib/python3.10/site-packages/notifications_utils/template.py", line 490, in do_nice_typography
    return compose1(
  File "/.venv/lib/python3.10/site-packages/notifications_utils/template.py", line 53, in compose1
    return_value = f(return_value)
  File "/.venv/lib/python3.10/site-packages/notifications_utils/formatters.py", line 193, in remove_whitespace_before_punctuation
    str(value)
  File "/.venv/lib/python3.10/site-packages/notifications_utils/field.py", line 108, in __str__
    return self.replaced
  File "/.venv/lib/python3.10/site-packages/notifications_utils/field.py", line 207, in replaced
    return re.sub(
  File "/usr/local/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/.venv/lib/python3.10/site-packages/notifications_utils/field.py", line 152, in replace_match
    raise NullValueForNonConditionalPlaceholderException
notifications_utils.field.NullValueForNonConditionalPlaceholderException
```

**Second Condition**: Email template has personalization field in subject, only.
VANotify Service, template ID `64b0953c-b7ea-4b48-b70f-d242ce5b17d2`
The Happy Path payload would be
```
{
    "template_id": "64b0953c-b7ea-4b48-b70f-d242ce5b17d2",
    "email_address": "<your email here>",
    "personalisation": {
        "thoughts": "TEST"
  }
}
```
1. In Postman, set service to VANotify with email_template_id set to `64b0953c-b7ea-4b48-b70f-d242ce5b17d2`
2. Use the POST send email route with that template ID and this payload (missing the subject personalization "thoughts"):
```
{
    "template_id": "64b0953c-b7ea-4b48-b70f-d242ce5b17d2",
    "email_address": "<your email here>",
    "personalisation": {}
}
```
3. Observe that the response is a 201 created, the email is sent/received and GET notifications for the notification ID returns a 200 and the relevant data.
4. Observe that the email's subject line contains the personalization field and span headers.
![Screen Shot 2023-08-04 at 1.45.10 PM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/1635c0f3-05c1-4cae-a39e-e892c066619a)

## Workaround
Is there something we can do to work around this issue in the meantime?

- None - always send the appropriate payloads.

## Impact/Urgency

Medium - inconvenient at best.
This is observed in the Staging environment as well, so is unrelated to any work happening in the current sprint.

## Expected Behavior

**Note: The majority of the work is in utils, but there will be minimal work in API to use the new utils version and throw the appropriate validation error. Please do both together in this ticket.**

- [x] Our service should validate any email subject personalization is present.
- [x] When an email subject personalization is missing from an otherwise good payload, the service should  return a 400 response about a missing property, not create a notification ID, and not send or retry the email.
- [x] Stretch goal: anytime a NullValueForNonConditionalPlaceholderException is raised, the message should never be retried.
- [x] Update the Slide deck with the key win and a demo slide

## QA Considerations
- [x] regression passes
- [x] test cases above in steps to reproduce a 400 error, not a 500 or a 201.

**Comment by kalbfled** [comment]
I transferred this ticket from Utils to API after discussing it with @cris-oddball.  My plan is to expand the template validation checks to yield a 400 response when somebody tries to send e-mail without required subject personalization.  That seems like the simplest solution.

**Comment by cris-oddball** [comment]
PR approved and merged, prrof of testing in dev supplied on PR. Will deploy to Perf and retest shortly.

**Comment by cris-oddball** [comment]
### QA TESTING IN PROGRESS

- [ ] TC01 using template id `e007cd96-39db-4f00-ac10-8128e96bf4cc` in Perf with `POST /v2/notifications/email,` when passing in both subject and body personalisation, the response is  201.
- [ ] TC02 The GET /v2/notification/<notification_id> for the above test returns a 200 and redacted subject/personalisation fields.
- [ ] TC03 using the same template, env and route, when failing to pass in subject personalisation, the response is a 400 with a validation error.
- [ ] TC04 using the same template, env and route, when failing to pass in body personalisation, the response is a 400 with a validation error.
