### ISSUE TITLE
[BUG] Incorrect timestamp parsing in pinpoint delivery events

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#555]
# Describe the Bug
Whenever we receive a delivery event from Pinpoint we try to load the notification from DB using pinpoint MessageId (store as reference).
If we cannot find a matching result in the DB, we retry processing the event (celery task) if the event happened within the last 5 minutes (app/celery/process_pinpoint_receipt_tasks.py#L132).
To calculate that we parse a timestamp that is part of the event.
The timestamp is `Unix time in milliseconds.` (https://docs.aws.amazon.com/pinpoint/latest/developerguide/event-streams-data-sms.html), however we use `iso8601.parse_date` which only parses string representation of date time objects.
This method throws `ParseError` exception that breaks the intended logic.

We need to replace the parsing with `datetime.fromtimestamp` method.
Since that method accepts timestamps only with a second precision, and the `event_timestamp` from AWS has millisecond precision, it has to first be transformed.

Example of log from production:
```
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 [2021-09-24 15:37:07,584: INFO/MainProcess] Received task: process-pinpoint-result[b7b9df5a-0dae-44ee-ba01-7118d5618140]
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 {"name": "delivery", "levelname": "INFO", "message": "received callback from Pinpoint with event_type of _SMS.BUFFERED and record_status of SUCCESSFULwith reference 060o2vccf715onip99r4s1k6vi7eb441tit20po0", "pathname": "/app/app/celery/process_pinpoint_receipt_tasks.py", "lineno": 73, "time": "2021-09-24T15:37:07", "requestId": "no-request-id", "application": "delivery", "logType": "application"}
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 [2021-09-24 15:37:07,594: INFO/ForkPoolWorker-4] received callback from Pinpoint with event_type of _SMS.BUFFERED and record_status of SUCCESSFULwith reference 060o2vccf715onip99r4s1k6vi7eb441tit20po0
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 {"name": "delivery", "levelname": "ERROR", "message": "Error processing Pinpoint results: <class 'iso8601.iso8601.ParseError'>", "pathname": "/app/app/celery/process_pinpoint_receipt_tasks.py", "lineno": 108, "exc_info": "Traceback (most recent call last):\n  File \"/app/app/celery/process_pinpoint_receipt_tasks.py\", line 128, in attempt_to_get_notification\n    notification = dao_get_notification_by_reference(reference)\n  File \"/usr/local/lib/python3.6/site-packages/notifications_utils/statsd_decorators.py\", line 17, in wrapper\n    raise e\n  File \"/usr/local/lib/python3.6/site-packages/notifications_utils/statsd_decorators.py\", line 14, in wrapper\n    res = func(*args, **kwargs)\n  File \"/app/app/dao/notifications_dao.py\", line 592, in dao_get_notification_by_reference\n    Notification.reference == reference\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py\", line 3473, in one\n    raise orm_exc.NoResultFound(\"No row was found for one()\")\nsqlalchemy.orm.exc.NoResultFound: No row was found for one()\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/app/app/celery/process_pinpoint_receipt_tasks.py\", line 79, in process_pinpoint_results\n    reference, notification_status, pinpoint_message['event_timestamp']\n  File \"/app/app/celery/process_pinpoint_receipt_tasks.py\", line 131, in attempt_to_get_notification\n    message_time = iso8601.parse_date(event_timestamp).replace(tzinfo=None)\n  File \"/usr/local/lib/python3.6/site-packages/iso8601/iso8601.py\", line 192, in parse_date\n    raise ParseError(\"Expecting a string %r\" % datestring)\niso8601.iso8601.ParseError: Expecting a string 1632497761944", "time": "2021-09-24T15:37:07", "requestId": "no-request-id", "application": "delivery", "logType": "application"}
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 [2021-09-24 15:37:07,606: ERROR/ForkPoolWorker-4] Error processing Pinpoint results: <class 'iso8601.iso8601.ParseError'>
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 Traceback (most recent call last):
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983   File "/app/app/celery/process_pinpoint_receipt_tasks.py", line 128, in attempt_to_get_notification
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983     notification = dao_get_notification_by_reference(reference)
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983   File "/usr/local/lib/python3.6/site-packages/notifications_utils/statsd_decorators.py", line 17, in wrapper
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983     raise e
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983   File "/usr/local/lib/python3.6/site-packages/notifications_utils/statsd_decorators.py", line 14, in wrapper
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983     res = func(*args, **kwargs)
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983   File "/app/app/dao/notifications_dao.py", line 592, in dao_get_notification_by_reference
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983     Notification.reference == reference
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3473, in one
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983     raise orm_exc.NoResultFound("No row was found for one()")
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 sqlalchemy.orm.exc.NoResultFound: No row was found for one()
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 During handling of the above exception, another exception occurred:
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 Traceback (most recent call last):
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983   File "/app/app/celery/process_pinpoint_receipt_tasks.py", line 79, in process_pinpoint_results
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983     reference, notification_status, pinpoint_message['event_timestamp']
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983   File "/app/app/celery/process_pinpoint_receipt_tasks.py", line 131, in attempt_to_get_notification
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983     message_time = iso8601.parse_date(event_timestamp).replace(tzinfo=None)
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983   File "/usr/local/lib/python3.6/site-packages/iso8601/iso8601.py", line 192, in parse_date
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983     raise ParseError("Expecting a string %r" % datestring)
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 iso8601.iso8601.ParseError: Expecting a string 1632497761944
prod-notification-api-log-group ecs/notification-celery/cf1776778fc0411aa45b3f608e607983 [2021-09-24 15:37:07,639: INFO/ForkPoolWorker-4] Task process-pinpoint-result[b7b9df5a-0dae-44ee-ba01-7118d5618140] retry: Retry in 300s
prod-notification-api-log-group ecs/notification-celery/1b75603c97d4406f9bb27075304d019f [2021-09-24 15:37:07,664: INFO/MainProcess] Received task: process-pinpoint-result[b7b9df5a-0dae-44ee-ba01-7118d5618140]  ETA:[2021-09-24 11:42:07.608622-04:00]

```

# Expected Behavior
Retry logic works correctly only if the event happened no longer than 5 minutes ago (when there might be some delay with persisting to the DB).

**Comment by miabecker** [comment]
Got it - closing now!
