### ISSUE TITLE
[BUG] 500 Error returned when UI token expires

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#571]
# Describe the Bug
Whenever the UI makes an API call with a token that has expired, API is not catching `jwt.exceptions.ExpiredSignatureError` exception thrown on `"/app/app/authentication/auth.py", line 84`

# To Reproduce
1. Login to UI
2. Wait until the token expires
3. Navigate somewhere in the UI
4. See error in dev console and cloudwatch logs.

# Expected Behavior
A `401 Token Expired` error should be returned by the API

# Actual Behavior 
API returns a `500` HTTP status code.

# Example log:
```
@ingestionTime	
1634054575043
@log	
171875617347:prod-notification-api-log-group
@logStream	
ecs/notification-api/8c945e164a8042ed991dbabff0ef31ed
@message	
{"name": "app", "levelname": "ERROR", "message": "Signature has expired", "pathname": "/app/app/errors.py", "lineno": 117, "exc_info": "Traceback (most recent call last):\n File \"/usr/local/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n rv = self.dispatch_request()\n File \"/usr/local/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n return self.view_functions[rule.endpoint](**req.view_args)\n File \"/app/app/authentication/auth.py\", line 131, in wrapper\n validate()\n File \"/app/app/authentication/auth.py\", line 107, in _validate_admin_auth_or_user_in_service\n validate()\n File \"/app/app/authentication/auth.py\", line 84, in _validate_user_in_service_or_platform_admin\n verify_jwt_in_request()\n File \"/usr/local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py\", line 67, in verify_jwt_in_request\n jwt_data, jwt_header = _decode_jwt_from_request(locations, fresh)\n File \"/usr/local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py\", line 261, in _decode_jwt_from_request\n decoded_token = decode_token(encoded_token, csrf_token)\n File \"/usr/local/lib/python3.6/site-packages/flask_jwt_extended/utils.py\", line 106, in decode_token\n return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)\n File \"/usr/local/lib/python3.6/site-packages/flask_jwt_extended/jwt_manager.py\", line 528, in _decode_jwt_from_config\n return _decode_jwt(**kwargs, allow_expired=allow_expired)\n File \"/usr/local/lib/python3.6/site-packages/flask_jwt_extended/tokens.py\", line 91, in _decode_jwt\n options=options,\n File \"/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py\", line 113, in decode\n decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)\n File \"/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py\", line 100, in decode_complete\n self._validate_claims(payload, merged_options, **kwargs)\n File \"/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py\", line 136, in _validate_claims\n self._validate_exp(payload, now, leeway)\n File \"/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py\", line 171, in _validate_exp\n raise ExpiredSignatureError(\"Signature has expired\")\njwt.exceptions.ExpiredSignatureError: Signature has expired", "time": "2021-10-12T16:02:54", "requestId": null, "application": "app", "logType": "application"}
@timestamp	
1634054574911
application	
app
exc_info	
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/app/authentication/auth.py", line 131, in wrapper
validate()
File "/app/app/authentication/auth.py", line 107, in _validate_admin_auth_or_user_in_service
validate()
File "/app/app/authentication/auth.py", line 84, in _validate_user_in_service_or_platform_admin
verify_jwt_in_request()
File "/usr/local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 67, in verify_jwt_in_request
jwt_data, jwt_header = _decode_jwt_from_request(locations, fresh)
File "/usr/local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 261, in _decode_jwt_from_request
decoded_token = decode_token(encoded_token, csrf_token)
File "/usr/local/lib/python3.6/site-packages/flask_jwt_extended/utils.py", line 106, in decode_token
return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
File "/usr/local/lib/python3.6/site-packages/flask_jwt_extended/jwt_manager.py", line 528, in _decode_jwt_from_config
return _decode_jwt(**kwargs, allow_expired=allow_expired)
File "/usr/local/lib/python3.6/site-packages/flask_jwt_extended/tokens.py", line 91, in _decode_jwt
options=options,
File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 113, in decode
decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 100, in decode_complete
self._validate_claims(payload, merged_options, **kwargs)
File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 136, in _validate_claims
self._validate_exp(payload, now, leeway)
File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 171, in _validate_exp
raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
levelname	
ERROR
lineno	
117
logType	
application
message	
Signature has expired
name	
app
pathname	
/app/app/errors.py
time	
2021-10-12T16:02:54
```

# Additional Context
Since currently the auth decorators try to authenticate using new tokens and in case of Auth errors try to authenticate using the old admin auth - the desired 401 Token Expired error might not be propagated all the way up to the response.

**Comment by philherbert** [comment]
This can be closed! Had some difficulties making its way through the pipeline, with twistlock failures and a defect found by the user flow tests, but now all fixed and good to close.
