### ISSUE TITLE
VA Profile integration: Alter opt-in/out lambda to handle the payload delivered by the loadbalancer

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#810]
The Profile integration opt-in/out lambda was originally written with the expectation that the request would be proxied from an AWS API Gateway2 instance, and that entailed a specific format.  However, [vanotify-infra 405](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/405) altered the infrastructure to utilize the loadbalancer as the proxy, and this changes the format of the request as received by the lambda.  The result is a KeyError.

VA Profile sent a request and received this 502 error:
```
{
  "httpAuditDetailed": {
    "type": "OUTGOING",
    "requestUri": "https://dev.api.notifications.va.gov/vaprofile/optinout",
    "requestTime": "2022-08-24T14:57:56Z",
    "requestMethod": "POST",
    "responseTime": "2022-08-24T14:57:59Z",
    "responseStatus": 502,
    "applicationName": "communication-vanotify",
    "sourceSystem": "VANOTIFY",
    "traceId": "63063c722692207238a75dbdcc07b3d1",
    "vaProfileTxAuditId": "0197ce2c-e854-4d67-8112-2ab4445d2e6e",
    "id": "14171da3-ea04-436a-bd13-0786d2c23797",
    "requestHeaders": {
      "Authorization": [
        "Bearer ...redacted...
      ],
      "Accept": [
        "text/plain, application/json, application/*+json, */*"
      ],
      "X-B3-SpanId": [
        "1590e7d6b09dc691"
      ],
      "txauditid": [
        "0197ce2c-e854-4d67-8112-2ab4445d2e6e"
      ],
      "X-B3-ParentSpanId": [
        "a75c86d640cf4b02"
      ],
      "X-B3-Sampled": [
        "0"
      ],
      "X-B3-TraceId": [
        "63063c722692207238a75dbdcc07b3d1"
      ],
      "Content-Length": [
        "591"
      ],
      "vaprofiletxauditid": [
        "0197ce2c-e854-4d67-8112-2ab4445d2e6e"
      ],
      "sourcesystem": [
        "VAPROFILE-TEST-PARTNER"
      ],
      "Content-Type": [
        "application/json"
      ]
    },
    "responseHeaders": {
      "Server": [
        "awselb/2.0"
      ],
      "Connection": [
        "keep-alive"
      ],
      "Content-Length": [
        "122"
      ],
      "Date": [
        "Wed, 24 Aug 2022 14:57:59 GMT"
      ],
      "Content-Type": [
        "text/html"
      ]
    },
    "requestPayload": "{\"txAuditId\":\"0197ce2c-e854-4d67-8112-2ab4445d2e6e\",\"identities\":[\"1008711236V315461^NI^200M^USVHA\",\"1531^PI^200VETS^USDVA\",\"32318816^PI^200CORP^USVBA\"],\"bios\":[{\"createDate\":\"2022-08-03T21:33:21Z\",\"updateDate\":\"2022-08-24T14:57:55Z\",\"txAuditId\":\"0197ce2c-e854-4d67-8112-2ab4445d2e6e\",\"sourceSystem\":\"VAPROFILE-TEST-PARTNER\",\"sourceDate\":\"2022-08-24T12:56:04Z\",\"communicationPermissionId\":47,\"vaProfileId\":1531,\"communicationChannelId\":1,\"communicationItemId\":5,\"communicationChannelName\":\"Text\",\"communicationItemCommonName\":\"Disability and pension deposit notifications\",\"allowed\":false}]}",
    "responsePayload": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"
  }
}
```

The logs reveal this error:
```
[ERROR] TypeError: string indices must be integers
Traceback (most recent call last):
  File "/var/task/va_profile_opt_in_out_lambda.py", line 198, in va_profile_opt_in_out_lambda_handler
    if "txAuditId" not in post_body or "bios" not in post_body or not isinstance(post_body["bios"], list):
```

The code expects a dictionary but received a JSON string.

**Comment by kalbfled** [comment]
@k-macmillan @jakehova 
UPDATE: VA Profile made another request after some changes and hit this error:
```
[ERROR] AssertionError
Traceback (most recent call last):
  File "/var/task/va_profile_opt_in_out_lambda.py", line 243, in va_profile_opt_in_out_lambda_handler
    make_PUT_request(post_body["txAuditId"], put_body)
  File "/var/task/va_profile_opt_in_out_lambda.py", line 335, in make_PUT_request
    assert va_root_pem is not None
```

This seems to be an infrastructure problem.  The VA root cert chain in SSM is no longer decryptable.

**Comment by kalbfled** [comment]
I fixed the assertion failure, and now I get a 502 caused by the connection timing-out.

**Comment by kalbfled** [comment]
"User flows" tests are failing for the master branch, which means they fail for my lambda branch.  That prevents me from deploying and testing the lambda.

**Comment by kalbfled** [comment]
Current problems:

1. I opened [vanotify-infra 433](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/433) to correct a permissions issue precluding database connectivity.
2. Running the database stored function yields an error that "id" (the primary key value) is missing in the query.  This is an auto-incrementing integer that should not be necessary.  The stored function works as intended when run on a local database container.
3. The 404 response to our PUT requests is probably due to Notify presenting the wrong certificate to Profile.  Profile's implementation expects from Notify the certificate associated with the environment's load-balancer, but that doesn't seem to be what they are getting.  It doesn't make sense to me that clients should be able programmatically to provide any certificate, so I suspect this is another infrastructure issue.

**Comment by kalbfled** [comment]
I created [vanotify-infra PR xxx]() to address the database permissions issue.  The traceback in the CloudWatch logs associated with the stored function is:

```
Traceback (most recent call last):
  File "/var/task/va_profile_opt_in_out_lambda.py", line 268, in va_profile_opt_in_out_lambda_handler
    c.execute(OPT_IN_OUT_QUERY, params)
psycopg2.errors.NotNullViolation: null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, 1531, 5, f, 1, 2022-09-03 15:06:10).
CONTEXT:  SQL statement "INSERT INTO va_profile_local_cache(va_profile_id, communication_item_id, communication_channel_id, source_datetime, allowed)
    VALUES(_va_profile_id, _communication_item_id, _communication_channel_id, _source_datetime, _allowed)
	ON CONFLICT ON CONSTRAINT uix_veteran_id DO UPDATE
    SET allowed = _allowed, source_datetime = _source_datetime
    WHERE _source_datetime > va_profile_local_cache.source_datetime
        AND va_profile_local_cache.va_profile_id = _va_profile_id
        AND va_profile_local_cache.communication_item_id = _communication_item_id
        AND va_profile_local_cache.communication_channel_id = _communication_channel_id"
PL/pgSQL function va_profile_opt_in_out(integer,integer,integer,boolean,timestamp without time zone) line 4 at SQL statement
```

**Comment by kalbfled** [comment]
The root cause of the stored function traceback is that the primary key for the cache table in dev is a UUID, whereas it should be an autoincrementing integer.  I discovered this problem early in the development process and altered the model definition and [migration 0343](https://github.com/department-of-veterans-affairs/notification-api/blob/master/migrations/versions/0343_create_VAProfileLocalCache.py).

I thought this approaches, versus creating a new migration, was safe because nobody had deployed the code to dev, thereby creating the table, but I must have been incorrect about that.  I'm going to fix this problem manually in the dev database and verify that it corrects the problem.  Then I will replicate it in the other deployment environments.

In dev:
```
notification_api=> \d va_profile_local_cache
                          Table "public.va_profile_local_cache"
          Column          |            Type             | Collation | Nullable | Default
---------------------------+--------------------------+-------------+----------+---------
 id                             | uuid                        |                  | not null |
```

Locally in a container:
```
notification_api=# \d va_profile_local_cache
                                               Table "public.va_profile_local_cache"
          Column          |            Type             | Collation | Nullable |                      Default                       
--------------------------+---------------------------+------------+----------+----------------------------------------------------
 id                            | integer                     |                | not null | nextval('va_profile_local_cache_id_seq'::regclass)
```

**Comment by kalbfled** [comment]
I resolved the stored function traceback by manually dropping the va_profile_local_cache table in the staging and dev environments and recreating it directly with SQL.  (Prod and perf were already correct.)  I also manually called the stored function and verified its correct operation.

Then I used Profile's Swagger endpoint to make a new POST request to trigger the VA Profile integration opt-in/out lambda, but I encountered a new problem that I don't think is a consequence of any change I've made:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'va_profile_opt_in_out_lambda': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)
Traceback (most recent call last):
```
Nothing follows the tracebook line.

**Comment by kalbfled** [comment]
Thanks to @k-macmillan for pointing me to [this Stackoverflow post](https://github.com/jpadilla/pyjwt/issues/612).  The above error was caused by the lambda being deployed with a newer version of the "cryptography" Python package that is not compatible with the AWS Lambda runtime.

I triggered the Profile integration lambda again using Profile's Swagger endpoint and verified the expected change in our development environment's database:
```
notification_api=> select * from va_profile_local_cache;
 id | va_profile_id | communication_item_id | allowed | communication_channel_id |   source_datetime
----+---------------+-----------------------+---------+--------------------------+---------------------
  6 |          1531 |                     5 | f       |                        1 | 2022-09-13 17:54:07
```

**Comment by kalbfled** [comment]
I opened [vanotify-infra#439](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/439) as part of the PUT request resolution.
