### ISSUE TITLE
Include the VA root certificates with the va_profile_opt_in_out lambda deployment

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#836]
[va_profile_opt_in_out_lambda](https://github.com/department-of-veterans-affairs/notification-api/tree/master/lambda_functions/va_profile) needs the VA's root certificate chain to authenticate VA Profile's server when making PUT requests to their endpoint.  As currently implemented, the lambda reads the certificates from SSM Parameter Store.

A better approach might be to emulate the [user flows lambda packaging process](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/lambda-functions.yml#L54) to make these root certificates part of the lambda deployment so they do not need to be read from outside the environment.

This ticket will need a corresponding infrastructure change to remove the SSM parameters.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/836?planning-poker) with Zenhub @trevor2718 @EvanParish @k-macmillan @ianperera @jessecanderson @cris-oddball @kalbfled

**Comment by kalbfled** [comment]
It's looking like we will need a new certificate for Profile integration.  We intended to utilize the ALB certificate for our (client) identity when making PUT requests to Profile, but we have not been able to obtain the private key, which is not accessible in ACM or Venafi after import.

**Comment by kalbfled** [comment]
Lambda execution fails because the permission acm:ExportCertificate (added to the associated infra change) is outside the permissions boundary.  @k-macmillan is opening a ticket to request to expand the boundary.

**Comment by kalbfled** [comment]
We obtained the expanded permission, but executing the lambda fails with this error:
```
[ERROR]	2022-09-26T18:45:46.222Z		An error occurred (ValidationException) when calling the ExportCertificate operation: Certificate ARN: arn:aws-us-gov:acm:us-gov-west-1:171875617347:certificate/d292129c-5c15-4477-af5f-34d3ef428892 is not a private certificate
Traceback (most recent call last):
  File "/var/task/va_profile_opt_in_out_lambda.py", line 100, in <module>
    response: dict = acm_client.export_certificate(
  File "/var/task/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ExportCertificate operation: Certificate ARN: arn:aws-us-gov:acm:us-gov-west-1:171875617347:certificate/d292129c-5c15-4477-af5f-34d3ef428892 is not a private certificate
```
I updated my AWS support ticket to request clarification.  Can we only used certificates created with AWS Private CA in this manner?
